# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # 매일 9AM KST (UTC 0AM)
  workflow_dispatch:
  
permissions:
  contents: read

  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Restore token.json
      env:
        TOKEN_JSON: ${{ secrets.YT_TOKEN_JSON }}
      run: |
        echo "$TOKEN_JSON" > token.json

    - name: Run script
      run: python create_yt_playlist.py

